version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker-config/php/Dockerfile  # Ссылка на Dockerfile для PHP
    volumes:
      - './public:/var/www/html'  # Публикация директории с проектом на контейнер

  nginx:
    image: nginx:latest  # Используем официальный образ Nginx
    ports:
      - "80:80"  # Прокси на порту 80
    volumes:
      - './public:/var/www/html'  # Подключение public директории проекта
      - './docker-config/nginx/conf.d:/etc/nginx/conf.d'  # Настройки Nginx

  mysql:
    image: mysql:8.4  # Используем образ MySQL 8.4
    ports:
      - "3306:3306"  # Прокси на порту 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Устанавливаем root пароль
    volumes:
      - './docker-config/database/mysql:/var/lib/mysql'  # Персистентность данных MySQL

  phpmyadmin:
    image: phpmyadmin:latest  # Используем образ phpMyAdmin для работы с базой данных
    ports:
      - "7070:80"  # Прокси на порту 7070
    environment:
      - PMA_HOST=mysql  # Устанавливаем хост для подключения
      - PMA_PORT=3306  # Устанавливаем порт для MySQL
